@startuml

'classes and interfaces
'--------------------------------------------------------

class Person {

int socialSecurityNumber
String firstName
String lastName


}

class Event {

private int arrId
private String arrName
private Person organizer
private ArrayList<Person> contestants


}

class DataRepository

class TerminalOut

class Main


'interactions
'-------------------------------------------------------
top to bottom direction

Event -right-> Person
Event o-- Person

@enduml