@startuml

'classes and interfaces
'--------------------------------------------------------

class Person {

int socialSecurityNumber
String firstName
String lastName

private void applyForEvent()

}



class Event {

private int arrId
private String arrName
private Person organizer
private ArrayList<Person> contestants

private void addContestant(Person contestant)
private void addOrganizer(Person organizer)

}


'interactions
'-------------------------------------------------------
top to bottom direction

Event -right-> Person
Event o-- Person

@enduml