@startuml

left to right direction

Deltaker ---down--> (View Event)
Deltaker ---down--> (Apply for Event)
Deltaker ---down--> (createAccount)

Arrangør ---up--> (Create Event)
Arrangør ---down--> (createAccount)


Arrangør ---up--> (View Event)


@enduml